# Generated by Django 4.2.5 on 2023-10-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full time", "Full Time Work"),
                            ("part time", "Part Time Work"),
                        ],
                        max_length=15,
                    ),
                ),
                ("description", models.TextField(max_length=1000)),
                ("published_at", models.DateTimeField(auto_now=True)),
                ("vacancy", models.IntegerField(default=1)),
                ("salary", models.IntegerField(default=0)),
                ("experience", models.IntegerField(default=1)),
            ],
        ),
    ]
