# Generated by Django 4.2.5 on 2023-10-06 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0002_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rel_category",
                to="job.category",
            ),
            preserve_default=False,
        ),
    ]
