# Generated by Django 4.2.5 on 2023-10-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0004_job_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
